apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mysql-ns
  name: mysql-pvc-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
