apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mysql-ns
  name: mysql-pv
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume"
